//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppValueListData
    {
        public int AppValueListId { get; set; }
        public System.Guid UniqueRowId { get; set; }
        public string AppValueListData1 { get; set; }
        public string AppValueListDescription { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
