//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppValueList
    {
        public int AppValueListId { get; set; }
        public string AppValueListTable { get; set; }
        public string AppValueListColumn { get; set; }
        public Nullable<int> AppValueListColumnCount { get; set; }
    }
}
