//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correspondence
    {
        public int CorrespondenceId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> StudyId { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public string RecipientAddress { get; set; }
        public string Topic { get; set; }
        public string TypeCorrespondence { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> DateOfCorrespondence { get; set; }
        public Nullable<int> VtgStaffId { get; set; }
        public Nullable<int> FollowupStaff1 { get; set; }
        public Nullable<int> FollowupStaff2 { get; set; }
        public Nullable<int> FollowupStaffEmailSent { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Study Study { get; set; }
    }
}
