//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosesIcd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiagnosesIcd()
        {
            this.AdverseEvents = new HashSet<AdverseEvent>();
            this.DiagnosesIcd1 = new HashSet<DiagnosesIcd>();
            this.MedicalHistories = new HashSet<MedicalHistory>();
        }
    
        public int DiagnosisId { get; set; }
        public Nullable<int> DiagnosisIdParent { get; set; }
        public string CodeId { get; set; }
        public string AsciiDesc { get; set; }
        public string AsciiShortDesc { get; set; }
        public int GroupLevel { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdverseEvent> AdverseEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosesIcd> DiagnosesIcd1 { get; set; }
        public virtual DiagnosesIcd DiagnosesIcd2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalHistory> MedicalHistories { get; set; }
    }
}
