//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EthicsApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EthicsApplication()
        {
            this.EthicsApplicationSubDocs = new HashSet<EthicsApplicationSubDoc>();
        }
    
        public int EthicsApplicationId { get; set; }
        public int StudyId { get; set; }
        public string Name { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string OrgApprovedBy { get; set; }
    
        public virtual Study Study { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EthicsApplicationSubDoc> EthicsApplicationSubDocs { get; set; }
    }
}
