//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformedConsent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformedConsent()
        {
            this.LinkSubjectStudyInformedConsents = new HashSet<LinkSubjectStudyInformedConsent>();
        }
    
        public int InformedConsentId { get; set; }
        public int StudyId { get; set; }
        public string Name { get; set; }
        public string Comments { get; set; }
        public string OrgApprovedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedWhen { get; set; }
    
        public virtual Study Study { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkSubjectStudyInformedConsent> LinkSubjectStudyInformedConsents { get; set; }
    }
}
