//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkSubjectMedication
    {
        public int SubjectMedicationLinkId { get; set; }
        public int PersonId { get; set; }
        public string NameMedication { get; set; }
        public string ProductOrGeneric { get; set; }
        public Nullable<int> DiagnosisId { get; set; }
        public string Reason { get; set; }
        public string DoseAmount { get; set; }
        public string DoseUnits { get; set; }
        public string DoseFrequency { get; set; }
        public string Route { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public Nullable<int> IsOngoing { get; set; }
        public Nullable<int> VtgStaffWitness { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
