//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkVtgStaffStudyRole
    {
        public int VtgStaffStudyRoleLinkId { get; set; }
        public int VtgStaffStudyLinkId { get; set; }
        public int StudyRoleId { get; set; }
    
        public virtual LinkVtgStaffStudy LinkVtgStaffStudy { get; set; }
        public virtual StudyRole StudyRole { get; set; }
    }
}
