//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkSubjectStudyInformedConsent
    {
        public int SubjectStudyInformedConsentLinkId { get; set; }
        public int SubjectStudyLinkId { get; set; }
        public int InformedConsentId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> VerbalConsentDate { get; set; }
        public Nullable<int> VerbalConsentBy { get; set; }
        public Nullable<System.DateTime> WrittenConsentDate { get; set; }
        public Nullable<int> WrittenConsentBy { get; set; }
    
        public virtual InformedConsent InformedConsent { get; set; }
        public virtual LinkSubjectsStudy LinkSubjectsStudy { get; set; }
    }
}
