//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkSubjectDoctorPractice
    {
        public int SubjectDoctorPracticeLinkId { get; set; }
        public int DoctorPracticeLinkId { get; set; }
        public int PersonId { get; set; }
        public Nullable<short> Priority { get; set; }
        public Nullable<int> ConsentToContactDr { get; set; }
        public string Comments { get; set; }
    
        public virtual LinkDoctorPractice LinkDoctorPractice { get; set; }
        public virtual Person Person { get; set; }
    }
}
