//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkVtgStaffStudy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinkVtgStaffStudy()
        {
            this.LinkVtgStaffStudyRoles = new HashSet<LinkVtgStaffStudyRole>();
        }
    
        public int VtgStaffStudyLinkId { get; set; }
        public int VtgStaffId { get; set; }
        public int StudyId { get; set; }
        public string DatabaseRole { get; set; }
        public string ConcatRoles { get; set; }
        public Nullable<int> IsBlindedYN { get; set; }
        public Nullable<System.DateTime> EffFrom { get; set; }
        public Nullable<System.DateTime> EffTo { get; set; }
    
        public virtual Study Study { get; set; }
        public virtual VtgStaff VtgStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkVtgStaffStudyRole> LinkVtgStaffStudyRoles { get; set; }
    }
}
