//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkSubjectsStudy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinkSubjectsStudy()
        {
            this.Visits = new HashSet<Visit>();
            this.LinkSubjectStudyInformedConsents = new HashSet<LinkSubjectStudyInformedConsent>();
        }
    
        public int SubjectStudyLinkId { get; set; }
        public int PersonId { get; set; }
        public int StudyId { get; set; }
        public string OfficialSubjectStudyNum { get; set; }
        public Nullable<int> StudyConsent { get; set; }
        public Nullable<System.DateTime> DateOfConsent { get; set; }
        public Nullable<int> ConsentForFutureUseOfSamples { get; set; }
        public Nullable<int> ConsentWitness { get; set; }
        public string Status { get; set; }
        public string WithdrawnReason { get; set; }
        public Nullable<System.DateTime> EffFrom { get; set; }
        public Nullable<System.DateTime> EffTo { get; set; }
        public string VisitStream { get; set; }
        public Nullable<System.DateTime> GpLetter1SentDate { get; set; }
        public Nullable<System.DateTime> GpLetter2SentDate { get; set; }
        public Nullable<System.DateTime> GpLetter3SentDate { get; set; }
        public Nullable<System.DateTime> FollowupReminder1SentDate { get; set; }
        public string WithdrawnReasonOther { get; set; }
    
        public virtual Study Study { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkSubjectStudyInformedConsent> LinkSubjectStudyInformedConsents { get; set; }
        public virtual Person Person { get; set; }
    }
}
