//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        public int MedicalHistoryId { get; set; }
        public int PersonId { get; set; }
        public int DiagnosisId { get; set; }
        public int BodySystemId { get; set; }
        public string Status { get; set; }
        public string YearDiagnosed { get; set; }
        public Nullable<int> AgeDiagnosed { get; set; }
        public string Comments { get; set; }
    
        public virtual BodySystem BodySystem { get; set; }
        public virtual DiagnosesIcd DiagnosesIcd { get; set; }
        public virtual Person Person { get; set; }
    }
}
