//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    
    public partial class ParticipantById
    {
        public int PersonId { get; set; }
        public Nullable<int> VtgNumber { get; set; }
        public string UMRN { get; set; }
        public Nullable<int> DbConsentYesNo { get; set; }
        public string DbConsentType { get; set; }
        public Nullable<System.DateTime> DbConsentDateLastConfirmed { get; set; }
        public Nullable<int> NewsletterConsentYesNo { get; set; }
        public Nullable<System.DateTime> NewsletterConsentDateLastConfirmed { get; set; }
        public Nullable<int> FutureVtgResearchConsentYesNo { get; set; }
        public Nullable<System.DateTime> FutureVtgResearchConsentDateLastConfirmed { get; set; }
        public Nullable<int> FutureThirdPartyResearchlConsentYesNo { get; set; }
        public Nullable<System.DateTime> FutureThirdPartyResearchConsentDateLastConfirmed { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string MiddleName { get; set; }
        public string PreferredName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Ethnicity { get; set; }
        public string PhoneWork { get; set; }
        public string PhoneMobile { get; set; }
        public string Email { get; set; }
        public string PreferredContactWritten { get; set; }
        public Nullable<int> Nok1PersonId { get; set; }
        public string Nok1Relationship { get; set; }
        public Nullable<int> Nok2PersonId { get; set; }
        public string Nok2Relationship { get; set; }
        public Nullable<int> HouseholdId { get; set; }
        public string RecruitmentSource { get; set; }
        public string Comments { get; set; }
        public string PreferredContactVerbal { get; set; }
        public Nullable<int> IsNok1ForKids { get; set; }
        public Nullable<int> IsNok2ForKids { get; set; }
        public Nullable<int> AgeInYrs { get; set; }
        public string AgeInYrMo { get; set; }
        public Nullable<int> AddresseeId { get; set; }
        public string NoK1Person { get; set; }
        public string NoK2Person { get; set; }
        public string AddressStreet { get; set; }
        public string AddressSuburb { get; set; }
        public string AddressPostcode { get; set; }
        public string AddressState { get; set; }
        public Nullable<int> ActiveAddress { get; set; }
        public Nullable<System.DateTime> LastConfirmedWhen { get; set; }
        public Nullable<int> LastConfirmedBy { get; set; }
        public string PhoneHome { get; set; }
        public Nullable<int> HouseholdAddressee { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<int> StudyId { get; set; }
        public string NicknameStudy { get; set; }
        public Nullable<int> SubjectStudyLinkId { get; set; }
        public string Status { get; set; }
        public string OfficialSubjectStudyNum { get; set; }
        public string WithdrawnReason { get; set; }
        public string WithdrawnReasonOther { get; set; }
        public Nullable<System.DateTime> EffFrom { get; set; }
        public Nullable<System.DateTime> EffTo { get; set; }
        public string VisitStream { get; set; }
    }
}
