//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireResult
    {
        public int QuestionnaireResultsId { get; set; }
        public int QuestionnaireId { get; set; }
        public int QuestionnaireResultsTypeId { get; set; }
        public string DatumValue { get; set; }
    
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual QuestionnaireResultsType QuestionnaireResultsType { get; set; }
    }
}
