//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnairesByVisit
    {
        public int QuestionnairesByVisitId { get; set; }
        public Nullable<int> TypeQuestionnaireId { get; set; }
        public int VisitScheduleId { get; set; }
    
        public virtual QuestionnaireType QuestionnaireType { get; set; }
        public virtual VisitSchedule VisitSchedule { get; set; }
    }
}
