//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        public int RecruitmentId { get; set; }
        public int StudyId { get; set; }
        public string SubjectInitials { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string RecruitmentSource { get; set; }
        public Nullable<int> IsEligible { get; set; }
        public string ReasonIfNotEligible { get; set; }
        public Nullable<int> IsEnrolled { get; set; }
        public string StudyNumber { get; set; }
        public Nullable<int> EnquiryNumber { get; set; }
    
        public virtual Study Study { get; set; }
    }
}
