//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamplesByVisit
    {
        public int SamplesByVisitId { get; set; }
        public Nullable<int> TypeSampleId { get; set; }
        public int VisitScheduleId { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Units { get; set; }
    
        public virtual SampleType SampleType { get; set; }
        public virtual VisitSchedule VisitSchedule { get; set; }
    }
}
