//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sample()
        {
            this.SubSamples = new HashSet<SubSample>();
        }
    
        public int SampleId { get; set; }
        public int VisitId { get; set; }
        public Nullable<int> TypeSampleId { get; set; }
        public Nullable<int> WasScheduledAtStudyLevelYN { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public Nullable<System.DateTime> CollectionTime { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Units { get; set; }
        public Nullable<int> RegisteredNurseId { get; set; }
        public Nullable<int> VtgStaffIdPresent { get; set; }
        public string Comments { get; set; }
        public Nullable<int> IsComplete { get; set; }
    
        public virtual SampleType SampleType { get; set; }
        public virtual Visit Visit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubSample> SubSamples { get; set; }
        public virtual VtgStaff VtgStaff { get; set; }
    }
}
