//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Study()
        {
            this.Correspondences = new HashSet<Correspondence>();
            this.EthicsApplications = new HashSet<EthicsApplication>();
            this.InformedConsents = new HashSet<InformedConsent>();
            this.LinkSubjectsStudies = new HashSet<LinkSubjectsStudy>();
            this.LinkVtgStaffStudies = new HashSet<LinkVtgStaffStudy>();
            this.Recruitments = new HashSet<Recruitment>();
            this.VisitSchedules = new HashSet<VisitSchedule>();
        }
    
        public int StudyId { get; set; }
        public string NameStudy { get; set; }
        public string NicknameStudy { get; set; }
        public string StudyType { get; set; }
        public Nullable<int> StudyCoordinator { get; set; }
        public Nullable<short> ExpNumSubjects { get; set; }
        public Nullable<System.DateTime> RecruitmentStartDate { get; set; }
        public Nullable<System.DateTime> RecruitmentEndDate { get; set; }
        public Nullable<System.DateTime> FirstVisitStartDate { get; set; }
        public Nullable<System.DateTime> FirstVisitEndDate { get; set; }
        public Nullable<double> SubjectMinAgeInYears { get; set; }
        public string SubjectMinAgeInequality { get; set; }
        public Nullable<double> SubjectMaxAgeInYears { get; set; }
        public string SubjectMaxAgeInequality { get; set; }
        public string BackgroundInfo { get; set; }
        public Nullable<int> IsCompletedYN { get; set; }
        public Nullable<System.DateTime> LastVisitEndDate { get; set; }
        public Nullable<System.DateTime> OfficialStartDate { get; set; }
        public Nullable<System.DateTime> OfficialEndDate { get; set; }
        public string GpMailoutStudyTitle { get; set; }
        public string GpMailoutStudyInfo { get; set; }
        public string GpMailoutStudyObjectives { get; set; }
        public Nullable<int> StudyIsCurrentlyBlindedYN { get; set; }
        public Nullable<int> IsSponsoredYN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Correspondence> Correspondences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EthicsApplication> EthicsApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformedConsent> InformedConsents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkSubjectsStudy> LinkSubjectsStudies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkVtgStaffStudy> LinkVtgStaffStudies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recruitment> Recruitments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitSchedule> VisitSchedules { get; set; }
        public virtual VtgStaff VtgStaff { get; set; }
    }
}
