//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    
    public partial class StudyVisitTasks
    {
        public int VisitScheduleId { get; set; }
        public int StudyId { get; set; }
        public int VisitOrder { get; set; }
        public string Description { get; set; }
        public Nullable<short> IdealDaysAfterPrevious { get; set; }
        public Nullable<short> MinDaysAfterPrevious { get; set; }
        public Nullable<short> MaxDaysAfterPrevious { get; set; }
        public Nullable<int> VisitOrderThatTimingIsRelativeTo { get; set; }
        public string Comments { get; set; }
        public string VisitStream { get; set; }
        public Nullable<int> Vaccine { get; set; }
        public Nullable<int> Samples { get; set; }
        public Nullable<int> Travel { get; set; }
        public Nullable<int> Questionnaire { get; set; }
    }
}
