//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSampleResult
    {
        public int SubSampleResultsId { get; set; }
        public int SubSampleId { get; set; }
        public int SubSampleResultsTypeId { get; set; }
        public string DatumValue { get; set; }
    
        public virtual SubSample SubSample { get; set; }
        public virtual SubSampleResultsType SubSampleResultsType { get; set; }
    }
}
