//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubSample()
        {
            this.SubSampleResults = new HashSet<SubSampleResult>();
        }
    
        public int SubSampleId { get; set; }
        public int SampleId { get; set; }
        public short SubSampleNumber { get; set; }
        public int VtgStaffIdSubSampler { get; set; }
        public Nullable<double> Millilitres { get; set; }
        public System.DateTime WhenProcessed { get; set; }
        public string FreezerOrTank { get; set; }
        public string ShelfOrStack { get; set; }
        public string BoxOrDrawer { get; set; }
        public string Position { get; set; }
        public Nullable<double> PercentPCD { get; set; }
        public string Comment { get; set; }
        public Nullable<int> AnalysedAtVTG { get; set; }
        public int AnalysisLocationsId { get; set; }
        public Nullable<System.DateTime> WhenSent { get; set; }
        public Nullable<int> VtgStaffIdSender { get; set; }
        public Nullable<int> VtgStaffIdReceiver { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedWhen { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedWhen { get; set; }
    
        public virtual AnalysisLocation AnalysisLocation { get; set; }
        public virtual Sample Sample { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubSampleResult> SubSampleResults { get; set; }
    }
}
