//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelReimbursement
    {
        public int TravelReimbursementId { get; set; }
        public int VisitId { get; set; }
        public Nullable<int> WasScheduledAtStudyLevelYN { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedWhen { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> PaymentCheckedBy { get; set; }
        public string Comments { get; set; }
        public Nullable<int> IsComplete { get; set; }
        public string WhyNotCompleted { get; set; }
    
        public virtual Visit Visit { get; set; }
    }
}
