//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination
    {
        public int VaccinationId { get; set; }
        public int VisitId { get; set; }
        public Nullable<int> TypeVaccinationId { get; set; }
        public Nullable<int> WasScheduledAtStudyLevelYN { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateAdministered { get; set; }
        public Nullable<System.DateTime> TimeAdministered { get; set; }
        public Nullable<System.DateTime> TimeRemovedFromFridge { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string SideSiteRoute { get; set; }
        public Nullable<int> RegisteredNurseId { get; set; }
        public Nullable<int> VtgStaffIdPresent { get; set; }
        public string Comments { get; set; }
        public Nullable<double> AmountInMls { get; set; }
        public Nullable<int> IsComplete { get; set; }
    
        public virtual VaccinationType VaccinationType { get; set; }
        public virtual Visit Visit { get; set; }
        public virtual VtgStaff VtgStaff { get; set; }
    }
}
