//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VtgStaffLocation
    {
        public int VtgStaffLocationId { get; set; }
        public string VtgStaffLocation1 { get; set; }
        public string Description { get; set; }
    }
}
