//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGWebAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VtgStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VtgStaff()
        {
            this.LinkVtgStaffStudies = new HashSet<LinkVtgStaffStudy>();
            this.Samples = new HashSet<Sample>();
            this.Studies = new HashSet<Study>();
            this.Vaccinations = new HashSet<Vaccination>();
            this.VtgStaffRequirements = new HashSet<VtgStaffRequirement>();
        }
    
        public int VtgStaffId { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string MiddleInitials { get; set; }
        public string Username { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public string VtgStaffLocation { get; set; }
        public string Details { get; set; }
        public string DbaseRole { get; set; }
        public string Password { get; set; }
        public Nullable<int> CurrentStudy { get; set; }
        public Nullable<System.DateTime> EffFrom { get; set; }
        public Nullable<System.DateTime> EffTo { get; set; }
        public Nullable<bool> DeletePrivilege { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkVtgStaffStudy> LinkVtgStaffStudies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample> Samples { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Study> Studies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccination> Vaccinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VtgStaffRequirement> VtgStaffRequirements { get; set; }
    }
}
